/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as contracts from './contracts'

export type { contracts }

export type { MockNFT } from './contracts/MockNFT'
export { MockNFT__factory } from './factories/contracts/MockNFT__factory'
