/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { BaseContract, BigNumber, BigNumberish, Signer, utils } from 'ethers'

import type { OnEvent, PromiseOrValue, TypedEvent, TypedEventFilter, TypedListener } from '../../../common'

export interface ICallPoolEventsInterface extends utils.Interface {
  functions: {}

  events: {
    'Activate(address)': EventFragment
    'BalanceChangedETH(address,uint256)': EventFragment
    'CallClosed(address,address,address,uint256,uint256)': EventFragment
    'CallOpened(address,address,uint256,uint8,uint8,uint256,uint40,uint40)': EventFragment
    'CollectProtocol(address,address,uint256)': EventFragment
    'Deactivate(address)': EventFragment
    'Deposit(address,address,address,uint256)': EventFragment
    'OffMarket(address,address,uint256)': EventFragment
    'OnMarket(address,address,uint256)': EventFragment
    'PreferenceUpdated(address,uint256,uint8,uint8,uint256)': EventFragment
    'PremiumReceived(address,address,uint256,uint256,uint256)': EventFragment
    'Withdraw(address,address,address,uint256)': EventFragment
    'WithdrawETH(address,address,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'Activate'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'BalanceChangedETH'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CallClosed'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CallOpened'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CollectProtocol'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Deactivate'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Deposit'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OffMarket'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OnMarket'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PreferenceUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PremiumReceived'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Withdraw'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'WithdrawETH'): EventFragment
}

export interface ActivateEventObject {
  account: string
}
export type ActivateEvent = TypedEvent<[string], ActivateEventObject>

export type ActivateEventFilter = TypedEventFilter<ActivateEvent>

export interface BalanceChangedETHEventObject {
  user: string
  newBalance: BigNumber
}
export type BalanceChangedETHEvent = TypedEvent<[string, BigNumber], BalanceChangedETHEventObject>

export type BalanceChangedETHEventFilter = TypedEventFilter<BalanceChangedETHEvent>

export interface CallClosedEventObject {
  nft: string
  user: string
  owner: string
  tokenId: BigNumber
  price: BigNumber
}
export type CallClosedEvent = TypedEvent<[string, string, string, BigNumber, BigNumber], CallClosedEventObject>

export type CallClosedEventFilter = TypedEventFilter<CallClosedEvent>

export interface CallOpenedEventObject {
  nft: string
  user: string
  tokenId: BigNumber
  strikePriceGapIdx: number
  durationIdx: number
  exercisePrice: BigNumber
  exercisePeriodBegin: number
  exercisePeriodEnd: number
}
export type CallOpenedEvent = TypedEvent<
  [string, string, BigNumber, number, number, BigNumber, number, number],
  CallOpenedEventObject
>

export type CallOpenedEventFilter = TypedEventFilter<CallOpenedEvent>

export interface CollectProtocolEventObject {
  sender: string
  recipient: string
  amount: BigNumber
}
export type CollectProtocolEvent = TypedEvent<[string, string, BigNumber], CollectProtocolEventObject>

export type CollectProtocolEventFilter = TypedEventFilter<CollectProtocolEvent>

export interface DeactivateEventObject {
  account: string
}
export type DeactivateEvent = TypedEvent<[string], DeactivateEventObject>

export type DeactivateEventFilter = TypedEventFilter<DeactivateEvent>

export interface DepositEventObject {
  nft: string
  user: string
  onBehalfOf: string
  tokenId: BigNumber
}
export type DepositEvent = TypedEvent<[string, string, string, BigNumber], DepositEventObject>

export type DepositEventFilter = TypedEventFilter<DepositEvent>

export interface OffMarketEventObject {
  nft: string
  owner: string
  tokenId: BigNumber
}
export type OffMarketEvent = TypedEvent<[string, string, BigNumber], OffMarketEventObject>

export type OffMarketEventFilter = TypedEventFilter<OffMarketEvent>

export interface OnMarketEventObject {
  nft: string
  owner: string
  tokenId: BigNumber
}
export type OnMarketEvent = TypedEvent<[string, string, BigNumber], OnMarketEventObject>

export type OnMarketEventFilter = TypedEventFilter<OnMarketEvent>

export interface PreferenceUpdatedEventObject {
  nft: string
  tokenId: BigNumber
  lowerStrikePriceGapIdx: number
  upperDurationIdx: number
  minimumStrikePrice: BigNumber
}
export type PreferenceUpdatedEvent = TypedEvent<
  [string, BigNumber, number, number, BigNumber],
  PreferenceUpdatedEventObject
>

export type PreferenceUpdatedEventFilter = TypedEventFilter<PreferenceUpdatedEvent>

export interface PremiumReceivedEventObject {
  nft: string
  owner: string
  tokenId: BigNumber
  premiumToOwner: BigNumber
  premiumToReserve: BigNumber
}
export type PremiumReceivedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  PremiumReceivedEventObject
>

export type PremiumReceivedEventFilter = TypedEventFilter<PremiumReceivedEvent>

export interface WithdrawEventObject {
  nft: string
  user: string
  to: string
  tokenId: BigNumber
}
export type WithdrawEvent = TypedEvent<[string, string, string, BigNumber], WithdrawEventObject>

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>

export interface WithdrawETHEventObject {
  user: string
  to: string
  amount: BigNumber
}
export type WithdrawETHEvent = TypedEvent<[string, string, BigNumber], WithdrawETHEventObject>

export type WithdrawETHEventFilter = TypedEventFilter<WithdrawETHEvent>

export interface ICallPoolEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: ICallPoolEventsInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {}

  callStatic: {}

  filters: {
    'Activate(address)'(account?: null): ActivateEventFilter
    Activate(account?: null): ActivateEventFilter

    'BalanceChangedETH(address,uint256)'(
      user?: PromiseOrValue<string> | null,
      newBalance?: null
    ): BalanceChangedETHEventFilter
    BalanceChangedETH(user?: PromiseOrValue<string> | null, newBalance?: null): BalanceChangedETHEventFilter

    'CallClosed(address,address,address,uint256,uint256)'(
      nft?: PromiseOrValue<string> | null,
      user?: PromiseOrValue<string> | null,
      owner?: null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      price?: null
    ): CallClosedEventFilter
    CallClosed(
      nft?: PromiseOrValue<string> | null,
      user?: PromiseOrValue<string> | null,
      owner?: null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      price?: null
    ): CallClosedEventFilter

    'CallOpened(address,address,uint256,uint8,uint8,uint256,uint40,uint40)'(
      nft?: PromiseOrValue<string> | null,
      user?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      strikePriceGapIdx?: null,
      durationIdx?: null,
      exercisePrice?: null,
      exercisePeriodBegin?: null,
      exercisePeriodEnd?: null
    ): CallOpenedEventFilter
    CallOpened(
      nft?: PromiseOrValue<string> | null,
      user?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      strikePriceGapIdx?: null,
      durationIdx?: null,
      exercisePrice?: null,
      exercisePeriodBegin?: null,
      exercisePeriodEnd?: null
    ): CallOpenedEventFilter

    'CollectProtocol(address,address,uint256)'(
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null
    ): CollectProtocolEventFilter
    CollectProtocol(
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      amount?: null
    ): CollectProtocolEventFilter

    'Deactivate(address)'(account?: null): DeactivateEventFilter
    Deactivate(account?: null): DeactivateEventFilter

    'Deposit(address,address,address,uint256)'(
      nft?: PromiseOrValue<string> | null,
      user?: null,
      onBehalfOf?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): DepositEventFilter
    Deposit(
      nft?: PromiseOrValue<string> | null,
      user?: null,
      onBehalfOf?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): DepositEventFilter

    'OffMarket(address,address,uint256)'(
      nft?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): OffMarketEventFilter
    OffMarket(
      nft?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): OffMarketEventFilter

    'OnMarket(address,address,uint256)'(
      nft?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): OnMarketEventFilter
    OnMarket(
      nft?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): OnMarketEventFilter

    'PreferenceUpdated(address,uint256,uint8,uint8,uint256)'(
      nft?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      lowerStrikePriceGapIdx?: null,
      upperDurationIdx?: null,
      minimumStrikePrice?: null
    ): PreferenceUpdatedEventFilter
    PreferenceUpdated(
      nft?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      lowerStrikePriceGapIdx?: null,
      upperDurationIdx?: null,
      minimumStrikePrice?: null
    ): PreferenceUpdatedEventFilter

    'PremiumReceived(address,address,uint256,uint256,uint256)'(
      nft?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      premiumToOwner?: null,
      premiumToReserve?: null
    ): PremiumReceivedEventFilter
    PremiumReceived(
      nft?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      premiumToOwner?: null,
      premiumToReserve?: null
    ): PremiumReceivedEventFilter

    'Withdraw(address,address,address,uint256)'(
      nft?: PromiseOrValue<string> | null,
      user?: PromiseOrValue<string> | null,
      to?: null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter
    Withdraw(
      nft?: PromiseOrValue<string> | null,
      user?: PromiseOrValue<string> | null,
      to?: null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter

    'WithdrawETH(address,address,uint256)'(
      user?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawETHEventFilter
    WithdrawETH(
      user?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawETHEventFilter
  }

  estimateGas: {}

  populateTransaction: {}
}
