/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import type { Provider, TransactionRequest } from '@ethersproject/providers'
import type { PromiseOrValue } from '../../../common'
import type { ErrorCodes, ErrorCodesInterface } from '../../../contracts/Errors.sol/ErrorCodes'

const _abi = [
  {
    inputs: [] as any,
    name: 'CP_ARRAY_LENGTH_UNMATCHED',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_CALLER_IS_NOT_FACTORY_OWNER',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_CAN_NOT_OPEN_A_POSITION_ON_SELF_OWNED_NFT',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_CAN_NOT_OPEN_CALL',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_DID_NOT_SEND_ENOUGHT_ETH',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_DURATION_TOO_LONG',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_GAP_OR_DURATION_OUT_OF_INDEX',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_INVALID_AMOUNT',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_INVALID_RECEIVER',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_NFT_ON_MARKET_OR_UNABAILABLE',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_NOT_ENOUGH_BALANCE',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_NOT_IN_THE_EXERCISE_PERIOD',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_NOT_THE_OWNER',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_PREMIUM_AND_ETH_UNEQUAL',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_STRIKE_GAP_TOO_LOW',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_STRIKE_PRICE_TOO_LOW',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [] as any,
    name: 'CP_TOO_LITTLE_PREMIUM_TO_OWNER',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

const _bytecode =
  '0x6101ea61003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106101155760003560e01c80638b7a2e6b116100ac578063ba6f6fff1161007b578063ba6f6fff1461018c578063bf480ec414610194578063da38f4d11461019c578063df2aef45146101a4578063ed5f7fb8146101ac57600080fd5b80638b7a2e6b1461016c57806391eabf361461017457806395168aa51461017c578063954002481461018457600080fd5b806351c42457116100e857806351c424571461014c578063558c0e9a146101545780636add4c0b1461015c5780636ea0eb471461016457600080fd5b80630c73f7201461011a5780632290440d1461013457806327aa65fd1461013c5780633fabcc6a14610144575b600080fd5b610122601181565b60405190815260200160405180910390f35b610122600181565b610122600381565b610122600281565b610122600a81565b610122600d81565b610122600b81565b610122600c81565b610122600e81565b610122600f81565b610122600881565b610122600781565b610122600481565b610122600981565b610122600681565b610122600581565b61012260108156fea26469706673582212204d5efa81edc1b9ee982247f7b8245969faf054cc52a3d10adf13cc7b46640d2664736f6c63430008090033'

type ErrorCodesConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>

const isSuperArgs = (xs: ErrorCodesConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
  xs.length > 1

export class ErrorCodes__factory extends ContractFactory {
  constructor(...args: ErrorCodesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args)
    } else {
      super(_abi, _bytecode, args[0])
    }
  }

  override deploy(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ErrorCodes> {
    return super.deploy(overrides || {}) as Promise<ErrorCodes>
  }
  override getDeployTransaction(overrides?: Overrides & { from?: PromiseOrValue<string> }): TransactionRequest {
    return super.getDeployTransaction(overrides || {})
  }
  override attach(address: string): ErrorCodes {
    return super.attach(address) as ErrorCodes
  }
  override connect(signer: Signer): ErrorCodes__factory {
    return super.connect(signer) as ErrorCodes__factory
  }

  static readonly bytecode = _bytecode
  static readonly abi = _abi
  static createInterface(): ErrorCodesInterface {
    return new utils.Interface(_abi) as ErrorCodesInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ErrorCodes {
    return new Contract(address, _abi, signerOrProvider) as ErrorCodes
  }
}
