/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokensSol from './Tokens.sol'
export type { tokensSol }
export type { MockedOracle } from './MockedOracle'
export type { NFTOracleTestUpgrade } from './NFTOracleTestUpgrade'
